apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "java-hello-world.fullname" . }}
  labels:
    {{- include "java-hello-world.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "java-hello-world.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "java-hello-world.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - java
                - -jar
                - app.jar
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - java
                - -jar
                - app.jar
            initialDelaySeconds: 5
            periodSeconds: 5
